export const data = {
    type:"Card-Rich",
    category : "Latest",
    heading : "Popular AI Tools that can increase your effectiveness",
    author : "Piyush arora",
    authorlink:"https://portfolio-livid-pi-76.vercel.app/",
    uploadDate :"2nd, June 2023",
    coverimage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQm0fPRB8uLQ1CeiInsW9lGD_-t0UsO-b21Q&usqp=CAU",
    coverimagealt:"Alt for cover image",
    content:[
        {
        coverimage:"https://images.pexels.com/photos/16115909/pexels-photo-16115909/free-photo-of-google-bard.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        SearchTags:"bigs",
        coverimagealt:"Alt of the card",
        title:"Google Bard",
        description:"Bard is a large language model from Google AI, It can generate text, translate languages write different kinds of creative content, and answer your questions in an informative way. It is still under development, but it has learned to perform many kinds of tasks",
        knowMore:"",         
        navigationLink:"https://bard.google.com/",
        },{
        coverimage:"https://images.pexels.com/photos/16037278/pexels-photo-16037278/free-photo-of-open-laptop-on-a-desk.jpeg?auto=compress&cs=tinysrgb&w=600",
        SearchTags:"tags3",
        coverimagealt:"Chat GPT alt image ai-tool chatbot",
        title:"ChatGPT",
        description:"ChatGPT is a large language model chatbot developed by OpenAI. It is trained on a massive dataset of text and code, and can generate text, translate languages, write different kinds of creative content, and answer your questions in an informative way",
        knowMore:"",         
        navigationLink:"https://chat.openai.com/",
        },{
        coverimage:"https://cdn.removal.ai/new-theme/remove.webp",
        SearchTags:"tags1",
        coverimagealt:"Background remover ",
        title:"removal.ai",
        description:"An AI-powered background remover that can remove the background from any image in seconds, free to use and can be used to create transparent, white, or customized backgrounds.",
        knowMore:"",         
        navigationLink:"https://removal.ai/",
        },{
        coverimage:"https://images.pexels.com/photos/669615/pexels-photo-669615.jpeg?auto=compress&cs=tinysrgb&w=600",
        SearchTags:"tags",
        coverimagealt:"Summarize-tech SummaryAI Video-Summary ",
        title:"Summarize.tech",
        description:"Get a summary of any long YouTube video, like a lecture, live event or a government meeting. Get output in points, paragraphs and essays for free !! Work like a PRO.  Powered by ChatGPT.",
        knowMore:"",         
        navigationLink:"https://www.summarize.tech/",
        },{
        coverimage:"https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8d3JpdGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
        SearchTags:"tags",
        coverimagealt:"Correct Language , 100% Free , ",
        title:"QuillBot",
        description:" QuillBot's free online grammar checker tool is designed to perfect your English writing by reviewing it for grammar, spelling, and punctuation errors. With its advanced AI capabilities, QuillBot identifies and suggests corrections for subject-verb agreement, word usage, sentence fragments, run-on sentences, and more, helping you refine your writing skills.",
        knowMore:"",         
        navigationLink:"https://quillbot.com/",
        },{
        coverimage:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Google_Translate_logo.svg/2048px-Google_Translate_logo.svg.png",
        SearchTags:"tags",
        coverimagealt:"Correct Language , 100% Free , ",
        title:"Google Translate",
        description:"Google Translate can be used to translate text, websites, documents, and even entire conversations. It is a valuable tool for travelers, students, and anyone who needs to communicate with people who speak other languages.",
        knowMore:"",         
        navigationLink:"https://translate.google.co.in/",
        },{
        coverimage:"https://letsenhance.io/static/654dee326e920a125e07424a2045f75c/4b49a/UN.avif",
        SearchTags:"tags",
        coverimagealt:"Image Editor , 100% Free , ",
        title:"Let's Enhance",
        description:"Image enhancement app Let’s Enhance can transform low-res images into clear and sharp pics to be proud of, using cutting-edge image processing algorithms. With Let’s Enhance you can scale up your images without compromising on quality, with the app’s algorithm able to expand any image while optimising the tone, texture, colour, and clarity.",
        knowMore:"",         
        navigationLink:"https://letsenhance.io/",
        },{
        coverimage:"https://tse4.mm.bing.net/th?id=OIP.Ny4BEpLIvzAZWxLbadwp5gAAAA&pid=Api&P=0&h=180",
        SearchTags:"tags",
        coverimagealt:"Audio Generation , 100% Free , ",
        title:"Big speak",
        description:"Big Speak allows you to generate realistic sounding audio from text. Powered by Streams.live, it uses a mix of machine learning algorithms to achieve the best voice generation technology.",
        knowMore:"",         
        navigationLink:"https://bigspeak.ai/",
    }
]
}